network.host: 0.0.0.0
cluster.name: mycluster
#自动生成
#node.name: ${HOSTNAME}
#node.master: false
#node.data: false
#path.data: /usr/share/elasticsearch/data
#path.logs: /usr/share/elasticsearch/logs
#bootstrap.mlockall: true
#network.host: 0.0.0.0
#network.publish_host: 192.168.8.10
#transport.tcp.port: 9300
#http.port: 9200
#index.refresh_interval: 5s
#script.inline: true
#script.indexed: true